#.bashrc

# source global definitions
if [ -f /etc/bashrc ] ; then
  . /etc/bashrc
fi

# Uncomment the following line if you dont like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

$ User specific aliases and funtions
cowsay 'Kevin say how you doin !'
