# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
. /etc/bashrc 
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions 
cowsay 'Tomato is a fruit not a vegetable'
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status H
